// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLM9TxZ5CiHp-9mZOj8qh3J3555oFS4kU',
    appId: '1:713439877328:web:babdd8d956d35507ff26d5',
    messagingSenderId: '713439877328',
    projectId: 'jotha-test',
    authDomain: 'jotha-test.firebaseapp.com',
    storageBucket: 'jotha-test.firebasestorage.app',
    measurementId: 'G-8W8BMRBM88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7620wVlHvxwdRVu-b9l-dXUI4WV6JRQk',
    appId: '1:713439877328:android:d58744888f40d809ff26d5',
    messagingSenderId: '713439877328',
    projectId: 'jotha-test',
    storageBucket: 'jotha-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHpMhqcK_IXyc5RrWNp4WdiU62h7aeE8',
    appId: '1:713439877328:ios:93486b2e675c4ab6ff26d5',
    messagingSenderId: '713439877328',
    projectId: 'jotha-test',
    storageBucket: 'jotha-test.firebasestorage.app',
    iosBundleId: 'com.example.jothaTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLM9TxZ5CiHp-9mZOj8qh3J3555oFS4kU',
    appId: '1:713439877328:web:27471eb4a0501670ff26d5',
    messagingSenderId: '713439877328',
    projectId: 'jotha-test',
    authDomain: 'jotha-test.firebaseapp.com',
    storageBucket: 'jotha-test.firebasestorage.app',
    measurementId: 'G-Z9Z7FVML8Z',
  );

}